### ISSUE TITLE
Problem installing magento-2-seo-extension 

### ISSUE THREAD

**Issue by Nym77** [mageplaza/magento-2-seo-extension#14]
Dears, 
    i am trying to install this extension in my local developing machine (Mac with MAMP php7 and Magento 2.1 ) 
I followed the instructions that i found here: 
https://docs.mageplaza.com/kb/installation.html#how-to-install-magento-2-extension
https://mageplaza.freshdesk.com/support/solutions/articles/6000132397-how-to-install-magento-2-extension

In particular I am using the command line installation and i am copying the folder magento-2-seo-extension in the root directory that in my case is 
/Applications/MAMP/htdocs/magento2

When I run the "setup:upgrade" command i noticed that the magenta-2-seo-extension is not in the list of module. 

Am I missing something?

**Comment by imsamthomas** [comment]
You should read installation guide if download from Mageplaza.com

If install from Github, you should run composer command line as github description

**Comment by imsamthomas** [comment]
```
composer require mageplaza/core-m2
composer require mageplaza/magento-2-seo-extension
php bin/magento setup:upgrade
```

**Comment by Nym77** [comment]
I noticed that there was a problem in the naming of the folder that now is solved. 
Now the config.php has the following modules: 

    'Mageplaza_Core' => 1,
    'Mageplaza_Seo' => 1,

however if I run the command "magento setup:upgrade" the command terminate early with when is attempting to update the schema 

If i remove the modules (     'Mageplaza_Core' => 0, 'Mageplaza_Seo' => 0, ) 

the command terminate successfully. 


Cache cleared successfully
File system cleanup:
/Applications/MAMP/htdocs/magento2/var/generation/Composer
/Applications/MAMP/htdocs/magento2/var/generation/Magento
/Applications/MAMP/htdocs/magento2/var/generation/Symfony
The directory '/Applications/MAMP/htdocs/magento2/var/di/' doesn't exist - skipping cleanup
Updating modules:
Schema creation/updates:
...
Module 'Mageplaza_Core':
Module 'Mageplaza_Seo':
Upgrading schema...
