### ISSUE TITLE
Fatal Error SEO

### ISSUE THREAD

**Issue by franknh23** [mageplaza/magento-2-seo-extension#15]
[SSHFILE_SEO.txt](https://github.com/mageplaza/magento-2-seo-extension/files/621520/SSHFILE_SEO.txt)

installed this extension in my server nexcess php7 and Magento 2.1 )
I followed the instructions that i found here:
https://docs.mageplaza.com/kb/installation.html#how-to-install-magento-2-extension
https://mageplaza.freshdesk.com/support/solutions/articles/6000132397-how-to-install-magento-2-extension

could not login or see my store : there has bin erroe with my request - 
so i had to use my back up.

**Comment by imsamthomas** [comment]
You may get the old version of SEO extension
We have fixed upgrade issue already.

Download latest version at Mageplaza: https://www.mageplaza.com/magento-2-seo-extension/ or Github https://github.com/mageplaza/magento-2-seo-extension or our site

**Comment by franknh23** [comment]
i did this and updatet my file now i am try o install 
and getting this 
[thewomen@sipsjc1-17 html]$ composer require mageplaza/magento-2-seo-extension
Using version ^1.1 for mageplaza/magento-2-seo-extension
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Installation request for mageplaza/magento-2-seo-extension ^1.1 -> satisfiable by mageplaza/magento-2-seo-extension[1.1.0].
    - mageplaza/magento-2-seo-extension 1.1.0 requires mageplaza/core-m2 dev-master -> satisfiable by mageplaza/core-m2[dev-master] but these conflict with your requirements or minimum-stability.


Installation failed, reverting ./composer.json to its original content.

**Comment by franknh23** [comment]
solved

**Comment by franknh23** [comment]
now missing the SEO in the admin panel -the Installation instruction are very bad written - you ever test this before put out??

**Comment by franknh23** [comment]
HERE me again the INSTALL INSTRUCTION ARE JUNK IF A USER  FOLLOW YOU DOC HE IS LOST MY SEO IS NOT SHOWING IN MY STORE - we follow your instruction - same thing with one step checkout - where is the command for the composer. If i use only  php bin/magento setup:upgrade

php bin/magento setup:static-content:deploy this will not work . That ridicules how you provide information for item you sell .

**Comment by franknh23** [comment]
mageplaza/magento-2-seo-extension 1.1.0 requires mageplaza/core-m2 dev-master -> no matching package found.

so i dont see any body they can use this in Magento2 maybe on 1.9  - we tried this several times

**Comment by WaPoNe** [comment]
Hi @franknh23 how do you solved this problem?

Problem 1
- Installation request for mageplaza/magento-2-seo-extension ^1.1 -> satisfiable by mageplaza/magento-2-seo-extension[1.1.0].
- mageplaza/magento-2-seo-extension 1.1.0 requires mageplaza/core-m2 dev-master -> satisfiable by mageplaza/core-m2[dev-master] but these conflict with your requirements or minimum-stability.

Installation failed, reverting ./composer.json to its original content.

**Comment by imsamthomas** [comment]
You should download SEO package from https://www.mageplaza.com/magento-2-seo-extension/
and follow the installation guide.

**Comment by imsamthomas** [comment]
You can use composer command like such `composer require mageplaza/magento-2-seo-extension`
https://packagist.org/packages/mageplaza/magento-2-seo-extension
