### ISSUE TITLE
setup::ugrade error

### ISSUE THREAD

**Issue by aemm2016** [mageplaza/magento-2-seo-extension#16]
this project had a change and it was changed 20hours to:
_How to install : Download the latest version at https://www.mageplaza.com/magento-2-seo-extension/ then follow installation guide_

if one is doing this, one will get following error:
Upgrading schema... PHP Fatal error:  Uncaught Error: Call to undefined method Magento\Setup\Module\DataSetup::create() in /var/www/magento/app/code/Mageplaza/Seo/Setup/UpgradeSchema.php:46
Stack trace:
#0 /var/www/magento/app/code/Mageplaza/Seo/Setup/UpgradeSchema.php(35): Mageplaza\Seo\Setup\UpgradeSchema->_addRobotsAttribute(Object(Magento\Setup\Module\Setup))
#1 /var/www/magento/setup/src/Magento/Setup/Model/Installer.php(849): Mageplaza\Seo\Setup\UpgradeSchema->upgrade(Object(Magento\Setup\Module\Setup), Object(Magento\Setup\Model\ModuleContext))
#2 /var/www/magento/setup/src/Magento/Setup/Model/Installer.php(779): Magento\Setup\Model\Installer->handleDBSchemaData(Object(Magento\Setup\Module\Setup), 'schema')
#3 /var/www/magento/setup/src/Magento/Setup/Console/Command/UpgradeCommand.php(73): Magento\Setup\Model\Installer->installSchema()
#4 /var/www/magento/vendor/symfony/console/Symfony/Component/Console/Command/Command.php(257): Magento\Setup\Console\Command\UpgradeCommand->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object( in /var/www/magento/app/code/Mageplaza/Seo/Setup/UpgradeSchema.php on line 46

whats wrong? I am no developer.

**Comment by aemm2016** [comment]
after ignoring imsamthomas 's last commit I downloaded the zip from github.
The installation went through. In the end it said:
_Please re-run Magento compile command_

I tried to follow this command.
**php -d set_time_limit=3600 -d memory_limit=1024M bin/magento setup:di:compile**
but got an issue:
_Compilation was started.
Repositories code generation... 1/7 [====>-----------------------]  14% 1 sec 46.0 MiBPHP Fatal error:  Class 'Mageplaza\Core\Helper\AbstractData' not found in /var/www/magento/app/code/Mageplaza/Seo/Helper/Data.php on line 9
Segmentation fault (core dumped)_

the modul project  is in my opinion not in a stadium, in which it could be in the github repository... please consider to provide a somewhat stable version (both: install & install instruction).
Someone trying out this only loses time, because this very unfinished work destroys a working magento environment. This costs Mageplaza reputation... you should think about that.

**Comment by refaelgold** [comment]
I get this error too ... hope you fix it

**Comment by vishalpawar-tudip** [comment]
Yes, I got the same error too, plz help us to solve this issue.

**Comment by imsamthomas** [comment]
We have fixed compilation issue, please pull latest version at https://github.com/mageplaza/magento-2-seo-extension
